### ISSUE TITLE
"Question-mark" titled icon is not a question mark

### ISSUE THREAD

**Issue by lt83870** [Legal-and-General/canopy#1085]
See: https://github.com/Legal-and-General/canopy/blob/master/projects/canopy/src/assets/icons/question-mark.svg

You may want to call this icon "filled-circle" instead or you may want to change it to be an actual question mark. Image or title should be changed.

**Comment by alexcanning** [comment]
It looks as though the question mark itself has been lost - this is what it should look like:

<img width="208" alt="image" src="https://user-images.githubusercontent.com/56020713/201157219-cbf9b165-ef24-4e8c-984b-e8f699f0edec.png">

**Comment by pauleustice** [comment]
@paul-request To look into this with @alexcanning

**Comment by michelleallendavey** [comment]
Sorry to throw a curveball @alexcanning @paul-request @Xinchro but this icon already exists in the library as query-fill 

https://github.com/Legal-and-General/canopy/blob/master/projects/canopy/src/assets/icons/query-fill.svg

We don't actually have one called question-mark in the Figma library. So I guess this issue involves checking if there are any uses of question-mark, replacing them with query-fill and deleting question-mark?

**Comment by paul-request** [comment]
Weirdly it is being used on OSS, so assume they are just seeing a circle then 🤔

**Comment by pauleustice** [comment]
[This broke in December 2020](https://github.com/Legal-and-General/canopy/commit/965fa2f0451cc7cee3c200079151493282c524e8). Think it's safe to say we can just remove it.

**Comment by pauleustice** [comment]
PR #1421 will fix this
