### ISSUE TITLE
link-menu now includes visually hidden text, assuming the link opens in a new window

### ISSUE THREAD

**Issue by markblandford** [Legal-and-General/canopy#1086]
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [x] Documentation
* [ ] Something else

### Steps to Reproduce

Look at the [link-menu component in Storybook](https://legal-and-general.github.io/canopy/?path=/story/components-link-menu-examples--standard-link-menu).

![image](https://user-images.githubusercontent.com/8008207/201954278-4a5bc1f0-92a2-4ad8-9f46-fd531d39372d.png)

#### Expected behaviour:

Not to have this visually hidden text, when the anchor doesn't actually open in a new tab.

#### Actual behaviour:

It looks like this visually hidden text, is automatically added when the `internal` parameter is `true`. Without checking the `target` is being set to `_blank` on the parent anchor element, I'm not sure this assumption can be made.

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [x] This problem started happening recently
* [ ] This problem started happening a while ago
* [ ] Unsure

Appears to have been introduced in v10.1.0.

## Configuration and environment

* [ ] This pertains to **local development**
* [ ] This pertains to **the CI**
* [ ] This pertains to **Storybook**

**Comment by elenagarrone** [comment]
Thanks @markblandford for raising this. You are right, we should add better logic to it - and also the logic in the template seem to be wrong as the `*ngIf` should say `if not internal add the visually hidden text`.
Does anyone in your team have time to fix this?

**Comment by markblandford** [comment]
Ah I got it, that makes more sense. So if `internal === false` then we have the 'opens in a new tab' text. 👍 

This was just something I noticed earlier with the existing links-menu we have. I may have time in a few days to have a go at addressing this.
