### ISSUE TITLE
lgPadding directive doesn't support breakpoints

### ISSUE THREAD

**Issue by pauleustice** [Legal-and-General/canopy#110]
The lgPadding (and related lgMargin) directives are really useful however as they doesn't support breakpoint-specific values, scss overrides are necessary to change non-desktop Canopy styles.

Perhaps the directives could take an object with values by breakpoint? e.g.

`<lg-card lgPadding="{ mobile: 'xxl' }">`

**Comment by thatguynamedandy** [comment]
We had this issue in the old repo, which I think links to it. https://github.com/canopy-collective/canopy/issues/249

The proposal was this...

lgMargin and lgPadding are useful escape hatches to tweak components without adding individual classes. I think a good advancement would be able to get them to provide different spaces for difference screen sizes.

For example the below will add a medium top padding for all screen sizes..

lgMarginTop="md"

This is good but what we may want to do is have different padding for different sizes, a potential API would be something like the below..

lgMarginTop="{ 'sm': 'md', md: 'xxl', 'lg': 'xxxl' }"

This would allow us to tailor the margin/padding to the screen resolution.

**Comment by owensgit** [comment]
I also like the idea of using an object to describe the breakpoints, whilst still allowing a simple string for an all-breakpoints solution, which would also avoid a breaking change.

**Comment by thatguynamedandy** [comment]
Links to #49 if anyone picks it up, not a massive task but maybe one up from 'good first issue'. @pauleustice would this do what you need?

**Comment by pauleustice** [comment]
Sorry both, I clearly need to tweak my notifications because I didn't see your replies! 🤦 

@thatguynamedandy Yes, that would cover it exactly. The only thing that may be confusing (and why I used `mobile` as a breakpoint key) is that we use the same sizing names for breakpoints and padding, so to me `{ sm: 'md' }` doesn't seem very intuitive.

**Comment by pauleustice** [comment]
Also worth considering that the approach above is at odds with how the [https://legal-and-general-canopy.netlify.app/?path=/story/directives--grid](grid directives) work
