### ISSUE TITLE
Prefix/suffix contrast issue when the input field is disabled

### ISSUE THREAD

**Issue by st3fun1** [Legal-and-General/canopy#1121]
## Prerequisites

* [X] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [X] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [X] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Use the `lg-input-field` component and add a suffix to the input field using `lgSuffix`
2. Disable the field 
3. Use **Wave** to detect the contrast issue.

#### Expected behaviour:

There shouldn't be any contrast issues.

#### Actual behaviour:

**Wave** detects a contrast issue.

#### Recurrence frequency:

* [X] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [X] Unsure

## Configuration and environment

* [X] This pertains to **local development**
* [ ] This pertains to **the CI**
* [x] This pertains to **Storybook**

## Additional Information

Example with the issue found by Wave:
![image](https://user-images.githubusercontent.com/12414812/209804434-3446b895-2aa0-4e5c-9505-bbbc3c77ad6e.png)

**Comment by elenagarrone** [comment]
@st3fun1 will close this as disabled fields don't have to meet the contrast ratio requirements: https://webaim.org/articles/contrast/
