### ISSUE TITLE
Error messages and warnings in unit test output

### ISSUE THREAD

**Issue by NemirStephan** [Legal-and-General/canopy#1158]
There are many instances or the following types of error in the unit test output

ERROR: 'NG0304: 'lg-heading' is not a known element (used in the 'LgPromoCardListTitleComponent' component template):
This can be fixed by mocking the unknown element (better than just adding CUSTOM_ELEMENTS_SCHEMA)

WARN: 'expected 'lg-link-menu-item

WARN: 'Forgot to flush TestBed? MockRender cannot be used without a reset after TestBed.get

It might also be a good idea to fail the tests on any console log, error or warn. That will prevent these errors creeping back in

**Comment by elenagarrone** [comment]
Thanks 👍 we have a ticket on the backlog to resolve the warnings 👍

**Comment by NemirStephan** [comment]
Closing issue as there is already a ticket on the backlog
