### ISSUE TITLE
Wrapped text in mobile tables is not right-aligned

### ISSUE THREAD

**Issue by github-tma8118** [Legal-and-General/canopy#1190]
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Add a Canopy table to the page
2. Set `<td lg-table-cell align="end">` on a cell
3. Insert some long text into that cell
4. View the table on a mobile device

#### Expected behaviour:

Text content is aligned to the right and wraps neatly onto new lines

#### Actual behaviour:

Text content appears to be left-align and does not wrap neatly onto new lines

<img width="349" alt="Screenshot 2023-05-09 at 10 57 49" src="https://user-images.githubusercontent.com/109232127/237063550-c684695e-77bd-4625-8979-7113a0c58a3e.png">

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [x] Unsure

## Configuration and environment

* [x] This pertains to **local development**
* [ ] This pertains to **the CI**
* [x] This pertains to **Storybook**

**Comment by pauleustice** [comment]
@jaynguyenslng To investigate and triage for relevance
