### ISSUE TITLE
Inputs inside the table looks elongated on Android devices

### ISSUE THREAD

**Issue by ciprianandrusca** [Legal-and-General/canopy#1198]
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Add a Canopy table to the page
2. Set `[showColumnsAt]="'sm'" `to the table
3. Add 2 columns (`<td lg-table-cell>`)
4. Add input in the 2nd column ( `<lg-input-field >`)
5. View the table on a Android devices

#### Expected behaviour:

Input fields are having the same width on Android and Apple devices. 
<img width="260" alt="image" src="https://github.com/Legal-and-General/canopy/assets/102965638/27f01654-5259-4bec-8137-50d0dd616bfd">

#### Actual behaviour:

Input fields are elongated on Android devices only. 

![image](https://github.com/Legal-and-General/canopy/assets/102965638/af2986b5-b8cb-4229-bfb3-3d534d15a71c)

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [x] This problem started happening a while ago
* [ ] Unsure

## Configuration and environment

* [x] This pertains to **local development**
* [ ] This pertains to **the CI**
* [x] This pertains to **Storybook**

**Comment by pauleustice** [comment]
@eduardh-landg To investigate within the next couple of weeks

**Comment by pauleustice** [comment]
@taraculpin To investigate in Ed's absence

**Comment by eduardh-landg** [comment]
I can confirm the issue is still persisting.
![image](https://github.com/Legal-and-General/canopy/assets/136433598/440e27a0-ec4e-43d6-b8d9-c4ad0b8b12fa)

**Comment by eduardh-landg** [comment]
I was able to replicate the same issue by creating a blank page with an input text. This demonstrates it is not a Canopy issue.
![image](https://github.com/Legal-and-General/canopy/assets/136433598/f6b8f6dd-88f9-44ec-862b-d976ff21340d)

**Comment by eduardh-landg** [comment]
Same behavior identified between Firefox simulating the resolution of an iPhone 15 and a iPhone 15 simulator. 
![image](https://github.com/Legal-and-General/canopy/assets/136433598/191b100b-a8af-4f5b-8f53-0aa6450febb7)

**Comment by eduardh-landg** [comment]
Conclusion: as long as specific behavior for width is not specified on the input element, the browser engine will manage it as seen in the reported issue. This is not _specifically_ a Canopy bug. Is there specific behavior expected from Canopy on this? @ciprianandrusca

**Comment by pauleustice** [comment]
We discussed during standup and agreed that the width of the input field is a responsibility of the integrator/consumer, rather than of Canopy itself.
