### ISSUE TITLE
Some unexpected padding has been added to `lg-details` components

### ISSUE THREAD

**Issue by github-tma8118** [Legal-and-General/canopy#1199]
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

It seems that this commit introduced some additional padding and it has upset a few of our layouts: https://github.com/Legal-and-General/canopy/commit/1b723f2153ce92b43e0b093d45690619cf9148c1

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Use Canopy v10.8.2
2. Add an `lg-details` component with a header and some content
3. Observe the amount of padding between the header and the content
4. Switch to Canopy v10.9.0
5. Rebuild the app and observe that there is extra space between the header and the content

#### Expected behaviour:

As per v10.8.2
<img width="917" alt="Screenshot 2023-06-09 at 09 36 11" src="https://github.com/Legal-and-General/canopy/assets/109232127/3dfe35f4-5434-4557-9cd2-207a30e8c801">

#### Actual behaviour:

With v.10.9.0
<img width="917" alt="Screenshot 2023-06-09 at 09 39 39" src="https://github.com/Legal-and-General/canopy/assets/109232127/38e2d4aa-490a-4599-8ea8-658b04397798">

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [x] This problem started happening recently
* [ ] This problem started happening a while ago
* [ ] Unsure

10.9.0

## Configuration and environment

* [ ] This pertains to **local development**
* [ ] This pertains to **the CI**
* [ ] This pertains to **Storybook**

**Comment by elenagarrone** [comment]
This is has been done because when focused the focus was too close to the content. See conversation here: https://github.com/Legal-and-General/canopy/pull/1181#issuecomment-1523342725
