### ISSUE TITLE
Issues with disabled lgInput

### ISSUE THREAD

**Issue by pauleustice** [Legal-and-General/canopy#126]
When an `lgInput` has a suffix (presumably the same for prefixes) and is disabled, the suffix does not have the grey background of the disabled input.

To replicate:

```
<lg-input-field>
  <input lgInput [disabled]="true" />
  <span lgSuffix>%</span>
</lg-input-field>
```

<img width="147" alt="Screenshot 2020-12-17 at 16 31 50" src="https://user-images.githubusercontent.com/1677737/102515650-e9118680-4085-11eb-9256-91a1b74c56b9.png">

There is also little visual feedback that the field is disabled. When an `lg-button` is disabled there is a `cursor: not-allowed` style on hover which could be useful for the input too.

**Comment by thatguynamedandy** [comment]
Thats interesting it might be to do with the way the input is being disabled. It appears to work in the Reactive form example..

https://legal-and-general-canopy.netlify.app/?path=/story/components-form-input--with-text-suffix

It's probably that the disabled property isn't getting set on the wrapper element.

**Comment by pauleustice** [comment]
@thatguynamedandy So it seems that it needs both the attribute (to disable the input) and the formControl's disabled property (to style the suffix) to be set to work. I feel like the component should handle setting the element's attribute itself

**Comment by Xinchro** [comment]
Closing as won't fix. Read above.
