### ISSUE TITLE
Banner message content link colours are not contrast compliant

### ISSUE THREAD

**Issue by mchand** [Legal-and-General/canopy#1417]
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-and-General/canopy/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-and-General/canopy/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

Using links inside the content of the banner message component results in non compliant link colours.

#### Expected behaviour:

The contrast of the links should be compliant.

#### Actual behaviour:

The links fail contrast checks.

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [x] Unsure

## Configuration and environment

* [x] This pertains to **local development**
* [ ] This pertains to **the CI**
* [x] This pertains to **Storybook**

## Additional Information

I understand from the documentation that this component is a work in progress but we should change the standard blue link colour  for both variants until we decide the link/button styling.

<img width="491" alt="Screenshot 2024-06-10 at 16 53 00" src="https://github.com/Legal-and-General/canopy/assets/7734137/0a63f4af-ba90-4bee-9307-01bdc653db96">

<img width="497" alt="Screenshot 2024-06-10 at 16 54 17" src="https://github.com/Legal-and-General/canopy/assets/7734137/1fd1084b-5a6f-49cf-aa4f-0dc3c3da690e">

It would be good to include some link text in the Storybook example similar to the Inline message component.

<img width="435" alt="Screenshot 2024-06-10 at 17 07 24" src="https://github.com/Legal-and-General/canopy/assets/7734137/fd459769-c7da-43de-a937-35bd8d0f6b38">

**Comment by paul-request** [comment]
@mchand this was a very quick initial implementation, as such only a generic and warning variant were created. We didn't have a need for links in our messages, so they were not implemented. If you need more variants and links, you could add that functionality as part of your work if that is possible?

**Comment by owensgit** [comment]
Looking at this it sounds similar to something that was proposed here: https://github.com/Legal-and-General/canopy/discussions/1276

Ideally, the variants mentioned here sound like they should be part of the [Variant directive](https://legal-and-general.github.io/canopy/?path=/story/helpers-directives-variant-examples--standard-variant), which creates the ability to style a component, such as the inline message, cards, etc with a specific colour treatment. This is a very composable and flexible approach, which I think is better than creating specific variants for the Banner Message only and would result in a reduction of duplicated code. If the proposal above were taken further it could be applied where needed.

**Comment by pauleustice** [comment]
Thanks @owensgit, I wasn't aware of the variants work that Elena had done. This sounds like a decent future feature, but not necessarily a fix for this issue. @mchand do you need links to work at present? If so, would you be open to picking up the work to add those styles?

**Comment by mchand** [comment]
@pauleustice, yes sure I can pick this up. I added the link styles to our app temporarily due to deadlines but can remove them after the PR is merged and Canopy upgraded. Thanks 👍
