### ISSUE TITLE
Simplify breadcrumb icon naming

### ISSUE THREAD

**Issue by aaronBery** [Legal-and-General/canopy#15]
In the breadcrumb component the container for icons has the class `lg-breadcrumb-item__container-hide-icons`  where `container-hide-icons` is an element on the `lg-breadcrumb-item`.

As the component has been scrutinised through usage it has become apparent the name is confusing and arguably sounds closer to a modifier than an element.

A simpler name could be `lg-breadcrumb-item__content-icons` suggesting the icons are set by the user (using content projection) distinguishing it from the backward and forward icons generated by the component.

**Comment by thatguynamedandy** [comment]
@aaronBery would you have a chance to resolve this one? I had a quick look but not sure it's just a simple rename. With the proposed rename we would end up with the following which gives a block of code two different block classes..

```html
  [ngClass]="{
    'lg-breadcrumb-item__container--visible-sm': isSmScreenFeaturedItem,
    'lg-breadcrumb-item__content-icons': hideIcons
  }"
```

**Comment by aaronBery** [comment]
@thatguynamedandy  I've been thinking about the mechanism in general and I think the logic for showing/hiding a non-chevron icons in hindsight feels over engineered, restrictive and confusing.

I would propose we align more closely to what we have since started doing in other components and introduce a mechanism whereby the consuming applications is responsible for setting the icon visibility

One approach could be to create a new breadcrumb-item-icon component and introduce a`hideIconAt` input.

Another approach would be to create a generic directive which could be applied on the icons to control their visibility at a certain screen width.

Other ideas from the community would be welcome on this!

**Comment by aaronBery** [comment]
I've taken another step back and realised what we are really doing with this component is controlling what is shown verses hidden on small screen devices as we always show all the items and icons on larger screens.

I've also identified that the `hideIcons` mechanism (which is what this issue was originally investigating) is pretty much redundant and as a result I've removed it on the draft [PR](https://github.com/Legal-and-General/canopy/pull/167) along with allowing the user to control which breadcrumb items are visible on small screen devices which is more in line with how we are now approaching Canopy components
