### ISSUE TITLE
Margin directive doesn't work on the Heading component

### ISSUE THREAD

**Issue by owensgit** [Legal-and-General/canopy#171]
Applying the `lgMargin` directive to `<lg-heading>`  doesn't override the margin  as you might expect - this is because the margin actually comes from the inner HTML heading tag (e.g. `<h2>` ). So when using `lgMargin`, it's applying the margin overrides to the wrapper element that Angular creates, not the `<h2>` itself.

**Comment by owensgit** [comment]
As suggested by @elenagarrone , a possible SCSS solution for this could be along the lines of:

```
.lg-heading[class^=lg-margin] > h1, h2, h3, etc... {
  margin/padding: inherit
}
```

**Comment by pauleustice** [comment]
Fixed in v8 as per the above
