### ISSUE TITLE
Issue with date-input component validation

### ISSUE THREAD

**Issue by AlexandruHoisan** [Legal-and-General/canopy#184]
The following is applicable for both sort-code component and date-input component:

When the sort-code component is empty or after the first interaction with one of it's inputs, clicking on submit we can see that the sort-code form-control status is valid even if that is not the case. The form-control is being set to its correct validation status right after. 
![Screenshot 2021-01-29 at 15 18 44](https://user-images.githubusercontent.com/68600084/106281746-4fbebe00-6248-11eb-9082-f06f634ddebf.png)
![Screenshot 2021-01-29 at 15 34 49](https://user-images.githubusercontent.com/68600084/106281748-50efeb00-6248-11eb-8637-83039ad49f6d.png)
![Screenshot 2021-01-29 at 15 13 19](https://user-images.githubusercontent.com/68600084/106281843-71b84080-6248-11eb-9579-d53f933d70a8.png)

This leads to successfully submitting a form even if the sort-code component is not valid.

This issue could potentially be caused by a time race between the validation calls of the individual input component and the sort-code component that wraps them up, or it might also be caused by the way Angular Reactive Forms handle the validation on complex nested forms( I am using complex here as in this scenario we have a formGroupDirective witch is also a AbstractControl).

To replicate, console.log() the form-control validity status when the `onSubmit` method is called
![Screenshot 2021-01-29 at 15 11 24](https://user-images.githubusercontent.com/68600084/106285895-b397b580-624d-11eb-8054-aa54afc9cc9f.png).

**Comment by elenagarrone** [comment]
The sort code has been fixed by removing the component and creating a directive that gets applied to the input. The sort code is now a single field.

I guess this is still an issue with the date field.
