### ISSUE TITLE
Deprecations & upcoming breaking changes (next)

### ISSUE THREAD

**Issue by owensgit** [Legal-and-General/canopy#196]
ℹ️  &nbsp; Small breaking changes are more easily consumed when shipped together in a major version bump.

💡  &nbsp; When identifying such a change, such as removing a CSS var, add a deprecation notice and where possible provide deprecation warnings in the console.

💬   &nbsp; Add a comment to this issue to log current deprecations and upcoming minor breaking changes.

🚀  &nbsp; At an appropriate time, they can be implemented together in one major release of Canopy (with some nice release notes).

♻️  &nbsp; When released, this issue can be closed down and another one spun up for the next batch.

---

> In future, we may want to consider creating a `next` branch to ship these changes for early adoption
> If this approach works well, we may want to consider creating an issue template for it.

**Comment by owensgit** [comment]
**Deprecated CSS vars**

- `--hero-bg-image`
- `--gradient-super-blue`

Marked with a CSS comment: `/* deprecated */`

Deprecated in: https://github.com/Legal-and-General/canopy/releases/tag/v5.2.0 
Original PR: https://github.com/Legal-and-General/canopy/pull/198

**Comment by andy-polhill** [comment]
Once we are happy with #282 we can probably remove the above deprecations, and be proud of ourselves for avoiding one extra breaking change.

There are a couple of additional issues flagged as 'breaking change' if we have capacity to bundle them in.

Angular also have a next branch raised for Angular 12, might be worth keeping one eye on that.

**Comment by elenagarrone** [comment]
@andy-polhill I'll have a look and add them to my pr.

**Comment by owensgit** [comment]
Closing this as these deprecations were successfully released in one go with other breaking changes 🥳

**Comment by owensgit** [comment]
Closing this as these deprecations were successfully released in one go with other breaking changes 🥳

**Comment by owensgit** [comment]
**Deprecated SCSS import in the following files**

- projects/canopy/src/lib/alert/alert.component.scss
- projects/canopy/src/lib/details/details.component.scss
- projects/canopy/src/lib/forms/validation/validation.component.scss

These files currently import `variants.scss` to make the global variant classes available in these components.

These imports need to be removed and a breaking change needs to be flagged so projects know that they need to import the new variants.scss file to get the variant classes, such as `.lg-variant--info`.
