### ISSUE TITLE
Update to Node SASS v5.0.0

### ISSUE THREAD

**Issue by owensgit** [Legal-and-General/canopy#205]
Being on Storybook v6 prevents us from updating to Node SASS v5.0.0, because it uses an older version of sass-loader which prevents the use of node-sass versions greater than v4. When we move to Storybook v6, we should update Node SASS as well.

Original PR that tried to update Node SASS, closed as it is blocked by Storybook - contains more info:
👉  https://github.com/Legal-and-General/canopy/pull/193

**Comment by andy-polhill** [comment]
Links to #35

**Comment by elenagarrone** [comment]
`node-sass` has been removed in favour of `dart-sass` in version `7.0.0`.

https://github.com/Legal-and-General/canopy/releases/tag/v7.0.0
