### ISSUE TITLE
Datepicker component

### ISSUE THREAD

**Issue by aaronBery** [Legal-and-General/canopy#206]
The ideal solution would have been to harness the native date picker however this isn't supported in all major browsers including Safari on MacOS.

One solution would be to create our own custom date picker. We would have full control over the component and we could keep the look and feel inline with other Canopy components.

The main consideration with this approach will however be how we handle mobile devices. Mobile users receive an excellent experience with native date pickers so any solution we create would need to offer a mobile friendly experience.

Alternatively we could detect mobile devices and fallback to the native picker. However there would be an overhead in detecting which device receives the native experience and could over complicate the component and possibly introduce external dependencies in the form of device detection libraries.

If we were to start developing a custom date picker component we would need an agreed design to capture the look and feel of the component (which takes into account our approach for handling mobile devices). 

Some technical considerations are that we currently use `date-fns` so it would make sense to use this in scenarios where we need to use date based functions.

**Comment by elenagarrone** [comment]
@aaronBery I would move this to the `discussions` tab
