### ISSUE TITLE
Improve use of a custom / header footer within a page component

### ISSUE THREAD

**Issue by markblandford** [Legal-and-General/canopy#21]
Currently, if you are using the PageComponent, the only way to have a header or footer, outside of the `main` element, is to use the `lg-header` and `lg-footer` directives. However, this prevents apps from using their own, custom header or footer.

The only current way I have found is to use the `lg-header` / `lg-footer` directive but to not import it into the application. However, IDEs complain about this.

![image](https://user-images.githubusercontent.com/8008207/95571570-9336b780-0a20-11eb-8968-14b9edd85917.png)

If I import the directives, the IDE complains and the app doesn't work:
![image](https://user-images.githubusercontent.com/8008207/95571962-2e2f9180-0a21-11eb-8e10-ea54dbee720b.png)

![image](https://user-images.githubusercontent.com/8008207/95572006-3d164400-0a21-11eb-9d0f-88711730f6d4.png)

Even though there aren't any duplicate components.

Ideally, I want to be able to do something like the following to use my own custom header / footer without any errors or warnings:

```html
<lg-page>
  <app-header lg-header></app-header>
  <app-content lgContainer>
    Page content
  </div>
  <app-footer lg-footer></app-footer>
</lg-page>
```

**Comment by thatguynamedandy** [comment]
Hi @markblandford there is a workaround for this in the notes for the component, which is to use `ngProjectAs`...

```html
<lg-page>
  <app-header ngProjectAs="[lg-header]"></app-header>
  <router-outlet></router-outlet>
  <app-footer ngProjectAs="[lg-footer]"></app-footer>
</lg-page>
``` 

I think this should give you what you need for now, however I don't think it's particularly intuitive. I raised a [similar issue on the old repository](https://github.com/canopy-collective/canopy/issues/250) to track it. I think your proposal makes sense, so I'm happy to leave this issue open as a way to track that improvement. Let me know if that workaround works though.

**Comment by markblandford** [comment]
That's great, cheers @thatguynamedandy, I figured there must have been another way.

**Comment by thatguynamedandy** [comment]
Modified the title as there could be case to improve the way we do this.

**Comment by Xinchro** [comment]
Closing as not an issue, documentation available in Storybook.
