### ISSUE TITLE
Margin directive doesn't work on button component

### ISSUE THREAD

**Issue by paul-request** [Legal-and-General/canopy#210]
Similar to: https://github.com/Legal-and-General/canopy/issues/171

The margin/padding classes get applied to the host element not the button element so the directive cannot be used to override the default margins.

```
<lg-button class"lg-margin-bottom--none">
   <button>My Button</button>
 </lg-button>
```

This could have been a conscious decision to keep things consistent. Not sure? Seems like the directive should be able to override this though.

As mentioned in the other ticket, we could add CSS to inherit these styles as a potential solution

**Comment by elenagarrone** [comment]
@paul-request I **think** it's because you are using the button component wrong 🤔 It's supposed to be:
```
<button lg-button variant="...">my button</button>
```

**Comment by paul-request** [comment]
> @paul-request I **think** it's because you are using the button component wrong 🤔 It's supposed to be:
> 
> ```
> <button lg-button variant="...">my button</button>
> ```

Ah, sorry, that is just kinda pseudo code. Let me check again, I will close if that's the case

**Comment by paul-request** [comment]
My mistake, implementation was incorrect.
