### ISSUE TITLE
Incrementing the unique id within brand icon component causes problems in unit tests

### ISSUE THREAD

**Issue by aaronBery** [Legal-and-General/canopy#248]
Setting the unique id (nextUniqueId) as done in the `LgBrandIconComponent`

causes issues in unit tests where assertions are made on the value of an elements id.

It would seem the problem is that the nextUniqueId is incrementing between tests making it impossible to know what it is going to be when writing a test.

On the current master branch (at the time of writing) the test `setting the name` for the following assertion 

`expect(fixture.nativeElement.querySelector('#lg-brand-icon-0')).toBeDefined();`

can return `null` so the test at present is often giving a false positive.

If the test is changed to

`expect(fixture.nativeElement.querySelector('#lg-brand-icon-0')).not.toBeNull();`

the test is liable to fail.

**Comment by aaronBery** [comment]
it may be worth considering other components affected by this same pattern when we consider a fix

**Comment by Xinchro** [comment]
Closing as won't fix.
