### ISSUE TITLE
Enums vs String literal types

### ISSUE THREAD

**Issue by thatguynamedandy** [Legal-and-General/canopy#25]
We have an ongoing discussion where we think these should be enums so that they can be referenced in code.
```ts
enum FilterVariant {
  SelectOne,
  SelectMultiple
}
```
Which means in the code we can do this instead of referring to the string value...
```ts
if (this.variant === FilterVariant.SelectMultiple) {
```
This comment is more for awareness, although I think this approach might be better, I'd rather we log it in an issue and then fix throughout the codebase, cc @aaronBery who I think has looked into it too)

_Originally posted by @thatguynamedandy in https://github.com/Legal-and-General/canopy/pull/20#discussion_r502309398_

**Comment by aaronBery** [comment]
This has been stale for a while. On the referenced issue I think I was checking to see if @elenagarrone  could dig up the arguments she had for using types over enums :-)

**Comment by elenagarrone** [comment]
I completely forgot about this! I'll try to write it down tomorrow ;)
