### ISSUE TITLE
Areas that require more documentation

### ISSUE THREAD

**Issue by andy-polhill** [Legal-and-General/canopy#301]
Starting this up as an issue to record places where documentation is lacking or of poor quality.

For anyone using Canopy this would be a really great place to help the community.

**Comment by andy-polhill** [comment]
putting the component wrapping element to use https://github.com/Legal-and-General/canopy/pull/386#discussion_r640632094

**Comment by pauleustice** [comment]
Outdated issue now that we have [Discussions](https://github.com/Legal-and-General/canopy/discussions), and have recently revamped all the documentation
