### ISSUE TITLE
Circular dependency and broken build on Windows

### ISSUE THREAD

**Issue by p-m-p** [Legal-and-General/canopy#325]
I'm not able to build from master branch on Win10 machine due to `build-styles` script and the Webpack configuration. Changing the copy plugin section to the below seems to resolve the issues.

There is also a circular dependency between the Toggle and Checkbox group components.

```javascript
    new CopyPlugin({
      patterns: [
        {
          from: 'projects/canopy/src/lib/**/*.scss',
          to: 'lib',
          flatten: false
        },
        {
          from: 'projects/canopy/src/styles/**/*.scss',
          to: 'styles',
          flatten: false,
        },
        {
          from: 'projects/canopy/src/assets/icons/*.svg',
          to: 'icons',
          flatten: true,
        },
        {
          from: 'projects/canopy/src/assets/brand-icons/*.svg',
          to: 'brand-icons',
          flatten: true,
        },
      ],
    }),
```

**Comment by pauleustice** [comment]
Closing this down as:

a) It's been inactive for a long time with no further complaints
b) We can't replicate as none of us use Windows machines

Happy to investigate with provision of further details and proof that Windows-enabling changes don't break MacOS.
