### ISSUE TITLE
Canopy Test App shows blank screen on startup

### ISSUE THREAD

**Issue by ABucin** [Legal-and-General/canopy#331]
The demo app shows a white screen and the following error(s) in the dev console:

<img width="513" alt="Screenshot 2021-04-26 at 12 32 52" src="https://user-images.githubusercontent.com/4033816/116061608-bdce2200-a68b-11eb-82b0-ba907c86b6b3.png">

**Comment by andy-polhill** [comment]
This is a recurrence of https://github.com/Legal-and-General/canopy/issues/79

**Comment by andy-polhill** [comment]
I think there are two stages to this issue
- The way the icon registry is loaded into the test project means there are effectively two instances of it.
- There is an ExpressionChangedAfterItHasBeenCheckedError in the table component

**Comment by pauleustice** [comment]
Closing as no longer an issue.
