### ISSUE TITLE
Issue with sort-code labels width

### ISSUE THREAD

**Issue by AlexandruHoisan** [Legal-and-General/canopy#338]
The following is applicable just for sort-code component

This problem arrises from the following fix: [label fix](https://github.com/Legal-and-General/canopy/commit/7e042c709ed90df977a1227fc004a61923d4d456)

In every div with the class `lg-sort-code__input` there is a label and a `lg-input-field`. The label has a class of
`lg-visually-hidden` but the problem is that the new width from the `lg-label` class is overriding the width from `lg-visually-hiden` class.
![Screenshot 2021-04-28 at 16 06 03](https://user-images.githubusercontent.com/68600084/116409841-e8aba800-a83c-11eb-948c-adffc341cda7.png)
![Screenshot 2021-04-28 at 16 06 33](https://user-images.githubusercontent.com/68600084/116409848-e9443e80-a83c-11eb-9362-a18eca603429.png)
![Screenshot 2021-04-28 at 16 08 49](https://user-images.githubusercontent.com/68600084/116409851-e9dcd500-a83c-11eb-9c03-fae1998c47da.png)

Because of this we get the following results on all devices:
![Screenshot 2021-04-28 at 16 17 43](https://user-images.githubusercontent.com/68600084/116410336-58219780-a83d-11eb-9ee4-4a3ce608603f.png)
![Screenshot 2021-04-28 at 16 17 30](https://user-images.githubusercontent.com/68600084/116410340-58ba2e00-a83d-11eb-8017-38f894ee55d6.png)

Posible solutions:
- getting rid of those labels altogether and leave just the `lg-input-field` in the `lg-sort-code__input` div.
- test different width properties. (The width introduced on the class `lg-label` was for a fix for IE11 so this might be tricky to test out)

**Comment by owensgit** [comment]
> test different width properties. (The width introduced on the class lg-label was for a fix for IE11 so this might be tricky to test out)

Teams are starting to drop support for IE11 (including ours) and Angular itself is doing so in v12. I wonder if we should think about removing that original fix, and officially dropping support for IE11 in Canopy? @elenagarrone what do you think?

**Comment by elenagarrone** [comment]
Closing this as it's not an issue anymore:
![Screenshot 2021-07-29 at 09 36 12](https://user-images.githubusercontent.com/8397116/127459989-d087b54b-ffe1-4ebe-8076-31d14a6541cd.png)
