### ISSUE TITLE
WAVE is highlighting a contrast issue with the skip to main content

### ISSUE THREAD

**Issue by NemirStephan** [Legal-and-General/canopy#431]
WAVE has highlighted the following contrast issue with the skip to main content link in the LgPageComponent

![image-20210622-132941](https://user-images.githubusercontent.com/22469863/123392055-8947eb00-d594-11eb-9a99-8ac159df2f57.png)

**Comment by paul-request** [comment]
This is because it has no explicit background color set, so WAVE will use whatever it determines the background to be. In our case it is the page background which is grey, so the contrast is not good enough. I think we can fix this by giving it a white background
