### ISSUE TITLE
Responsive Brand Icon sizing

### ISSUE THREAD

**Issue by andy-polhill** [Legal-and-General/canopy#488]
The `size` input of the brand icon could be extended so that it has responsive options. e.g. one size for small, one for large etc. 

_Originally posted by @andy-polhill in https://github.com/Legal-and-General/canopy/pull/485#discussion_r672921210_

**Comment by andy-polhill** [comment]
The implementation approach might link to #362

**Comment by Xinchro** [comment]
Closing as won't do. Currently seen as unnecessary functionality and there are other ways of sizing the icons.
