### ISSUE TITLE
Remove support for IE11

### ISSUE THREAD

**Issue by elenagarrone** [Legal-and-General/canopy#563]
We should remove support for IE11 within the codebase - e.g review browserslist, polyfills, css vars package, etc.

See also issue #78 as related to IE11.

This change should go into the `next` branch.

**Comment by paul-request** [comment]
Do we want to do this? If a consumer wants to support IE11, then they wouldn't be able to use this would they?

**Comment by aaronBery** [comment]
> Do we want to do this? If a consumer wants to support IE11, then they wouldn't be able to use this would they?

fair point but I'm not sure IE11 is officially supported by Microsoft so it feels wrong to bloat our code and support additional dependencies...that's my fairly hardline stance on IE11 :-p

**Comment by elenagarrone** [comment]
IE11 is going end of life on on the 15th of June 2022 so maybe we can stop adding specific code for it from now on and then remove support after that date?

**Comment by elenagarrone** [comment]
Released in [v8.0.0](https://github.com/Legal-and-General/canopy/releases/tag/v8.0.0)
