### ISSUE TITLE
Storybook markdown on the typography page is wrong...    

### ISSUE THREAD

**Issue by lt83870** [Legal-and-General/canopy#57]
…the breakdown into Purpose / Usage got corrupted…
https://canopy-e66e57.netlify.app/?path=/story/typography--headings

**Comment by thatguynamedandy** [comment]
I've checked and this issue is not present in the new deployment, we will decommission the old netlify deployment soon.
https://legal-and-general-canopy.netlify.app/?path=/story/typography--headings
