### ISSUE TITLE
Tabs component - incorrect font size on tab buttons

### ISSUE THREAD

**Issue by owensgit** [Legal-and-General/canopy#585]
The [Tabs Component](https://legal-and-general.github.io/canopy/?path=/story/components-tabs-tabbed-content--standard) seems to be rendering with a very large font and extra spacing inside the tab buttons:

<img width="1168" alt="Screenshot 2021-10-13 at 08 59 21" src="https://user-images.githubusercontent.com/1943532/137091787-3d1e335a-b583-4d0f-9da9-c4950454a146.png">

This doesn't seem to happen on the tabbed navigation version:

<img width="1171" alt="Screenshot 2021-10-13 at 09 00 04" src="https://user-images.githubusercontent.com/1943532/137091893-d10c5fbc-ce96-4b8a-a26d-892167628b58.png">

The styling of the tab buttons on the tabbed content version, need to be updated to match the tabbed navigation one.

**Comment by elenagarrone** [comment]
This has been resolved as part of https://github.com/Legal-and-General/canopy/pull/696.
