### ISSUE TITLE
Remove the support of deprecated pipe module

### ISSUE THREAD

**Issue by HarshaDewani** [Legal-and-General/canopy#609]
Currently, the Pipe module is deprecated. This is due to the fact that we now have separate modules for the camel and kebab case. This means that we can now import them individually instead of importing the whole pipe module.

PR that deprecated the Pipe module -
https://github.com/Legal-and-General/canopy/pull/573/files

This should be a breaking change and hence needs to be merged on next branch.

**Comment by owensgit** [comment]
@HarshaDewani looks like this is done in https://github.com/Legal-and-General/canopy/pull/610

I think you forgot to add this issue number to the commit :) 

I've also added this to https://github.com/Legal-and-General/canopy/issues/315

I'll close this ticket but feel free to reopen if I've got it wrong!
