### ISSUE TITLE
Quick Action label misaligned

### ISSUE THREAD

**Issue by alexcanning** [Legal-and-General/canopy#671]
Both link and button Quick Actions have misaligned labels. The label should be horizontally aligned with the icon in the middle of the button, but has dropped down:

<img width="631" alt="Screenshot 2022-01-11 at 15 54 25" src="https://user-images.githubusercontent.com/56020713/148977534-092ea294-ed54-4120-892c-c59d001560bd.png">

https://legal-and-general.github.io/canopy/iframe.html?id=components-quick-action--link
https://legal-and-general.github.io/canopy/iframe.html?id=components-quick-action--button

Quick action specs: https://legalandgeneral.invisionapp.com/console/Canopy---Specs-cknlj6aj81j0u01yz3e5ssrmv/cknlj8vfz1kiw01ymemal31bm/inspect

**Comment by elenagarrone** [comment]
@alexcanning that's very weird - it's completely fine for me 🤔 
![Screenshot 2022-01-11 at 16 32 08](https://user-images.githubusercontent.com/8397116/148982913-356c03e6-c027-48e4-a9d2-936144859b45.png)

Is that in a specific project? My guess is that maybe they have some style overriding the line height?

**Comment by alexcanning** [comment]
I can see it live on MyAccount and in Storybook in Chrome, just checked in Incognito mode. In Safari it seems to be fine!

**Comment by elenagarrone** [comment]
Are you using a super duper screen?

This is Chrome for me on all three of my monitors it looks fine

https://user-images.githubusercontent.com/8397116/148985206-658abf52-5058-4b0c-8cbf-2f50fd46784c.mov

**Comment by alexcanning** [comment]
I figured out that it's because I've sourced my version of Roboto from Creative Cloud - if I deactivate, it picks up the webfont and displays correctly. 🤦🏻‍♂️
