### ISSUE TITLE
Suppressing component margin on buttons (and maybe other compoments)

### ISSUE THREAD

**Issue by andy-polhill** [Legal-and-General/canopy#70]
By default we add a bottom margin to a lot of components. This gives them the correct vertical spacing and means they can be dropped into a component without any additional work, it also keeps the vertical rhythm consistent. A good example of this is form fields in a form.

However as @p-m-p pointed out this can be pain in certain scenarios, a particular example: when using buttons in a non vertical layout the margin needs to be individually over written each time a button is used.

The [lgMargin directive](https://legal-and-general-canopy.netlify.app/?path=/story/directives--margin) helps to do this on the odd occasions, but a facility to do it globally would help. One option could be to override the css variables, currently we have one called `--component-margin` which controls the vertical spacing. We could extend this to be more granular and have `--button-margin` which maps to `--component-margin` . So you could then override either the button variable to control the buttons or the global one to control all component margins. I'm not sure the best way of doing the overrides, e.g. could it be done [programatically](https://css-tricks.com/updating-a-css-variable-with-javascript/) in someway without any visual quirks.

**Comment by Xinchro** [comment]
Closing this as not an issue. Won't implement.
