### ISSUE TITLE
Bullet point turns to oval on smaller screen sizes when the label text is longer

### ISSUE THREAD

**Issue by Zimann** [Legal-and-General/canopy#827]
## Prerequisites

* [ ] I have checked the [open Issues](https://github.com/Legal-General-Group-Digital/frontend-platform/issues) to see if this has already been raised
* [ ] I have searched the [closed Issues](https://github.com/Legal-General-Group-Digital/frontend-platform/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] Component -  lg-radio-button

### Steps to Reproduce

1. Use a long text inside the `lg-radio-button` tags 
2. Select a small screen size (tablet or phone)
3.  You can see that the radio button turns into an oval and the selection styling is off-center

#### Expected behaviour:

The radio button stays round and selection styling stays in the center.
The radio button should align to the first row of a longer label.

#### Recurrence frequency:

* [ ] Occurs every time

## Package version

* [ ] Unsure

## Configuration and environment

* [ ] This pertains to **local development**
* [ ] This pertains to **Storybook**

## Additional Information

<img width="243" alt="image" src="https://user-images.githubusercontent.com/20334064/165973066-20d5b3e0-4e16-4881-bd42-4274d766fd7c.png">

**Comment by HarshaDewani** [comment]
I also have another question. Does the bullet point always be positioned at the center or should it be positioned at the top?
