### ISSUE TITLE
Checkbox group focus alignment

### ISSUE THREAD

**Issue by Devaney** [Legal-and-General/canopy#925]
## Description

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Use the lg-checkbox-group or lg-segment-group and focus it from the keyboard

#### Expected behaviour:
The focus on the group would be aligned correctly

#### Actual behaviour:
The focus is hidden in areas and overlapping elements from within the group.

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [x] Unsure

## Configuration and environment

* [x] This pertains to **local development**
* [ ] This pertains to **the CI**
* [x] This pertains to **Storybook**

**Comment by pauleustice** [comment]
Solved by PR #957
