### ISSUE TITLE
Time-delay icon hardcoded fill property

### ISSUE THREAD

**Issue by lt83870** [Legal-and-General/canopy#93]
Hi, in my latest PR I introduced the "time-delay" icon to the icons set, this was approved and merged. 

When the icon is seen in Storybook it renders just like all others, i.e. black by default as it is supposed to inherit the colour of the parent element. This icon, however, is permanently black as it has a hard-coded fill="#333" property in the path element of the svg rendered, which needs to go. 
Here is the time-delay icon html structure:
![image](https://user-images.githubusercontent.com/65162434/100727542-4c30c700-33be-11eb-91f9-87c426a18aad.png)
And here is another one, where we can see the fill property is unset. 
![image](https://user-images.githubusercontent.com/65162434/100728069-fc063480-33be-11eb-9baf-d44b6c57bd3b.png)

@james-hayden-ellis can provide an updated svg. 

Thanks for fixing this. 

Leo

**Comment by elenagarrone** [comment]
Hi @lt83870, I think we can do that using `svgo`. I'm just about to create a PR with the fix :)

**Comment by lt83870** [comment]
@james-hayden-ellis and I reviewed his composition of the svg and he is not doing anything different to what he did for other icons. Somehow, however, the fill is being set for this icon. 

I am guessing you guys (@thatguynamedandy et al) can fix this some other way. 

Cheers

**Comment by elenagarrone** [comment]
> @james-hayden-ellis and I reviewed his composition of the svg and he is not doing anything different to what he did for other icons. Somehow, however, the fill is being set for this icon.
> 
> I am guessing you guys (@thatguynamedandy et al) can fix this some other way.
> 
> Cheers

Yes, I've just created a PR for it so that the `fill` attributes gets stripped out automatically: https://github.com/Legal-and-General/canopy/pull/94

**Comment by lt83870** [comment]
Awesome, thanks @elenagarrone and approvers for the prompt corrective action. 👏👏👏
