### ISSUE TITLE
lg-primary-message - VoiceOver adds extra details to interactive elements within the message

### ISSUE THREAD

**Issue by kata-lin** [Legal-and-General/canopy#937]
## Prerequisites

* [x] I have checked the [open Issues](https://github.com/Legal-General-Group-Digital/frontend-platform/issues) to see if this has already been raised
* [x] I have searched the [closed Issues](https://github.com/Legal-General-Group-Digital/frontend-platform/issues?q=is%3Aissue+is%3Aclosed) to see if a similar bug has been fixed in the past

## Description

This bug affects:

* [ ] GitHub workflows
* [x] Component
* [ ] Config
* [ ] Performance
* [ ] Tooling / Frameworks
* [ ] Documentation
* [ ] Something else

### Steps to Reproduce

1. Go to: https://legal-and-general.github.io/canopy/?path=/story/components-primary-message--standard-primary-message
2. Start VoiceOver
3. With the tab key go to the first interactive element within the lg-primary-message component

#### Expected behaviour:

The label and the type of interactive element is announced.

#### Actual behaviour:

VoiceOver also announces extra words regarding the lg-primary-message component.

#### Recurrence frequency:

* [x] Occurs every time
* [ ] Occurs intermittently
* [ ] Unsure

## Package version

* [ ] This problem started happening recently
* [ ] This problem started happening a while ago
* [x] Unsure

## Configuration and environment

* [x] This pertains to **local development**
* [ ] This pertains to **the CI**
* [x] This pertains to **Storybook**

## Additional Information

We think that the **role: alert** attribute is causing this due to this reference found on https://developer.mozilla.org/: The alert role should only be used for text content, not interactive elements such as links or buttons. 

It looks like the **role: alertdialog** would be more appropriate due to the interactive elements within the lg-primary-message component. (The alertdialog role should only be used for alert messages that have associated interactive controls.)

**Comment by elenagarrone** [comment]
FYI this is also happening in the `lg-alert` component whenever there is a link.

Steps to reproduce:
1. Go to: https://legal-and-general.github.io/canopy/?path=/story/components-alert--standard-alert
2. Select one of the following variants: `success`, `error`, `warning` (these are the only variants that have `role=alert`)
3. Start VoiceOver
4. With the tab key go to the link

**Comment by elenagarrone** [comment]
I've asked our accessibility consultant about this issue and this was the reply:

> Regarding the Primary Message alert, using NVDA the announcement was clear. When navigating to the link, it only read the link text, but other content could be reached and read using other keyboard controls, which is expected.
I notice in the Github entry that users are using VoiceOver. We have found that some screen readers interpret information differently compared to others. While VoiceOver is a popular screen reader for Apple users, it represents a smaller segment of accessibility users in general. It is likely that the alert issue you've identified is a bug with VoiceOver and will probably be corrected in a future update.
Again, as this couldn't be replicated from our side and the code appears correct, I do not believe that any further action is required.

I will close this issue. We can always re-open if we think it affects more than just VoiceOver.
